### ISSUE TITLE
$.browser.mozilla problem with jQuery 1.9.1 and 2.0

### ISSUE THREAD

**Issue by zeroxme** [jethrolarson/placeholder-augment#2]
line 27 if($.browser.mozilla && $.browser.version.slice(0,3) == "1.9")
make a problem with with jQuery 1.9.1 and 2.0 so what i suggest is to use Modernizr.input.autocomplete coz it's more generic than $.browser

**Comment by jethrolarson** [comment]
Fixed it last year b3e16b9168fd3e4301a421385f55e80da425a923
